monolog:
    handlers:
        sentry:
            type:  raven
            dsn:   '%env(SENTRY_DSN)%'
            level: notice
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event", "!app"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        app:
            type: stream
            level: debug # all levels
            path: "%kernel.logs_dir%/%kernel.environment%.app.log"
            channels: [app]
